### ISSUE TITLE
Classical Extras plugin makes Picard hang after a couple of albums.

### ISSUE THREAD

**Issue by hiccup2** [musicbrainz/picard-plugins#134]
As briefly discussed on the forum, after processing a few albums with this plugin active, Picard will hang.
Restarting Picard will fix it briefly, but will freeze again after a few albums.
[Picardini.zip](https://github.com/metabrainz/picard-plugins/files/1565770/Picardini.zip)

W10x64
No scripts or other plugins running.

**Comment by Sophist-UK** [comment]
I have just had a look at the code and it could definitely benefit from some performance improvements.

Obvious things like making constant arrays and regular expressions class constants rather than redefining them inside a method would be beneficial.

But it also looks like it does an awful lot of loop processing which (knowing Python) can almost certainly be rewritten significantly more efficiently.

All that said, I haven't spotted any memory leaks which might cause it to hang, though I note that it does create class properties which persist and which could grow over time.

**Comment by MetaTunes** [comment]
I'd welcome any code improvements from a Python expert! I am well aware that it has got a bit spaghetti-like.
Re the reported issue, I have run my test database against the hiccup2's picard.ini and it causes a persistent failure to load the same 8 albums (out of 122 in the current test set). These albums load fine using my picard.ini. When I have had a problem like this before it was because of cross-contamination of class variables. I'll do a bit more digging.
Re the plans for the code. I'd like to stabilise 0.8.7 before inviting any attempts to re-engineer it. I have some minor un-released improvements that also need to be incorporated. This should form the basis for a v0.9 to be a pull request. The final (planned) version 1.0 is intended to incorporate additional functionality for instruments/ genres/ periods etc. After that it should be pretty complete and it will be time to look at migrating to Picard 2.0.

**Comment by MetaTunes** [comment]
OK, I think I know what the problem is. The "Works and Parts" option "Use cache" has been turned off. When there are two albums loaded that have a work in common, the second one will try and look up the works again. Not only is this inefficient, it also confuses the queue manager into thinking it hasn't got all the works, so it waits.... So the simple work-round solution is to enable "Use cache" (the default) and it should all run OK. I'll run my big test to double check.
The question remains as to how to prevent this. I'll look at a code fix, but I really don't want people turning cache off and forgetting as it does make things run slower. The only reason for turning off cache is to re-fetch data after a MB or structure change. So as well as a code fix, I may make it so that cache will automatically be turned on for each new session, regardless of how it was left at the end of the previous session.

**Comment by MetaTunes** [comment]
Test database runs fine with cache turned on

**Comment by Sophist-UK** [comment]
This may NOT be an issue of Picard caching as I cannot see why that would cause this (it is PyQt caching actually).

It looks like you used my albumartist_website method of avoiding simultaneous calls - are you sure it is working ok?

**Comment by MetaTunes** [comment]
It's the custom caching of the works hierarchy by the plugin which is the issue, not Picard. Your method is working fine. I just hadn't envisaged that people would load a lot of albums with caching turned off so I hadn't tested that.

**Comment by Sophist-UK** [comment]
I can't see why having caching turned off should be a problem - and I never tested that with `albumartist_website`. So I would be interested to know what you find out when you debug this.

**Comment by MetaTunes** [comment]
It's because the cache in my plugin holds the works hierarchy. If a second album with the same work is loaded but the cache is off, it queues the works to look up but the counting assumes they were found from cache. Unless the queue count returns to 0, the end of album processing will not run. So it is entirely a problem with my code - I just need to look and find out exactly why and where it is happening - but probably not tonight.

**Comment by MetaTunes** [comment]
v0.8.8 should fix this see https://community.metabrainz.org/t/classical-extras-plugin/300217/120

**Comment by MetaTunes** [comment]
@hiccup2 : I assume this is now fixed and can be closed?

**Comment by hiccup2** [comment]
Yes, I am pretty sure it's fine now.
(I did a couple of tests after the update, but after that have spend most of my 'Picard time' on my non-classical albums)

**Comment by hiccup2** [comment]
I'm a bit new to this github stuff. Should I click 'Close', or should only the developer do that?

**Comment by MetaTunes** [comment]
Heh! Me too. I don't see a "close" button, so I'm assuming only you can close it.

**Comment by hiccup2** [comment]
Close in 3..2..1..
