### ISSUE TITLE
Classical Extras: Error on a certain release

### ISSUE THREAD

**Issue by aereaux** [musicbrainz/picard-plugins#146]
Lately, I have been getting the following error on [this album](https://musicbrainz.org/release/5b79f6bb-0055-4bcd-a61c-c15bc238fa52/):
```Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/picard/webservice.py", line 315, in _process_reply
    self._handle_reply(reply, request, handler, xml, refresh)
  File "/usr/lib/python2.7/site-packages/picard/webservice.py", line 304, in _handle_reply
    handler(document, reply, error)
  File "/home/user/.config/MusicBrainz/Picard/plugins/classical_extras.zip/classical_extras/__init__.py", line 4018, in work_process
  File "/home/user/.config/MusicBrainz/Picard/plugins/classical_extras.zip/classical_extras/__init__.py", line 4210, in work_process_metadata
IndexError: list assignment index out of range
```

I'm not sure what exactly is causing it, though.  I am using [this release](https://github.com/MetaTunes/picard-plugins/releases/tag/v0.9.1).  My config file is [test.txt](https://github.com/metabrainz/picard-plugins/files/1882673/test.txt), it should be very close to the default.

Ping @MetaTunes.

Thanks.

**Comment by MetaTunes** [comment]
Hi @aereaux , I can't reproduce that at the moment. Which version of Classical Extras are you using?
Sorry - missed it in the post - 0.9.1 - I'll look again. Meanwhile, can you say whether the problem is occurring when you load the files into Picard, or also when you just use the tagger button in MB?

**Comment by aereaux** [comment]
It looks like it's also happening when I use the tagger button on musicbrainz.

**Comment by MetaTunes** [comment]
Not exactly sure what the problem is. I have run my copy of v0.9.1 on this album and it does fail but in a different way. I had spotted and fixed a number of small bugs which I think may have influenced this behaviour and these fixes are in the next release (v0.9.2). I have tested 0.9.2 against your album and it works (for me). I will release v0.9.2 asap but, as it also contains some major functionality additions (genres, instruments, keys, work dates, periods), I need to complete testing and documentation first - should be within a week, though.

**Comment by aereaux** [comment]
OK, great, thanks.  If you wanted to upload the new version as a prerelease or something, I could test it out.  Otherwise, no worries, I can just wait.

**Comment by MetaTunes** [comment]
v0.9.2 is pretty much done and is available as a pre-release at https://github.com/MetaTunes/picard-plugins/releases/tag/v0.9.2
I hope that fixes this issue. I would be grateful for any feedback before I publicise the new release.

**Comment by aereaux** [comment]
As far as I can tell, this issue no longer occurs.  Thanks!

Edit:  Actually, let me try another test quickly.

**Comment by aereaux** [comment]
OK, actually, the plugin fails before being loaded now:

```E: 17:37:28 Plugin 'classical_extras' : Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/picard/plugin.py", line 301, in load_plugin
    plugin_module = importer.load_module(_PLUGIN_MODULE_PREFIX + name)
  File "/home/user/.config/MusicBrainz/Picard/plugins/classical_extras.zip/classical_extras/__init__.py", line 7522, in <module>
  File "/home/user/.config/MusicBrainz/Picard/plugins/classical_extras.zip/classical_extras/__init__.py", line 247, in get_references_from_file
UnboundLocalError: local variable 'period_dict_list' referenced before assignment
```

**Comment by MetaTunes** [comment]
Sorry! Could you try downloading again?

**Comment by aereaux** [comment]
OK, that fixed it, and it does seem to be working now.  Again, thanks for making this plugin.

**Comment by aereaux** [comment]
OK, the only problem I still see is that there is a missing `;` in the default Period Map.

**Comment by MetaTunes** [comment]
That will be fixed when I release it. Meantime, I assume you just added it in the box.
