### ISSUE TITLE
BPM plugin causes metadata tab not to update

### ISSUE THREAD

**Issue by madmouser1** [musicbrainz/picard-plugins#200]
When bulk updating tracks with bpm values using https://github.com/metabrainz/picard-plugins/commit/aaf833de6fe0d4e56163a8678316f75ffe2df141 the editor area become unresponsive. Assistance is needed to resolve. This is tested against Picard Version 2.1.1.dev2

Example of behavior: 
![4 - lots of files not working 1 - reworked](https://user-images.githubusercontent.com/7412512/51464450-7d212900-1d5d-11e9-8795-6d157b094e3d.png)

**Comment by phw** [comment]
One possible reason might be https://github.com/metabrainz/picard-plugins/commit/3c24df9a15f2b4f7e628b9249f20846b8f7eef38#diff-2be19b656c43a2630cca1797a79607bb

You might try to uncomment the call to `file.update()`

**Comment by phw** [comment]
I digged into this, the reason is actually that the BPM module is using Picard's default thread pool, and that is also used by the UI to update the metadata boxes. So if the BPM module queues up a lot of calculations it starves the thread pool needed for the UI updates.

I updated the plugin to use it's own thread pool, see #205 . But maybe we should update Picard to have a thread pool dedicated to UI updates that must not be used by plugins.

**Comment by phw** [comment]
I have merged the PR, but actually we decided to fix this in Picard. So the PR improves only a situation when closing Picard, in this case the BPM could cause the Picard process to continue for quite a while after the user had already closed the window.

The fix with response times will be included in Picard 2.1.3 which should be out in a week or two. This allowed us to fix the issue cleanly without increasing the complexity in plugins. At the time of the Picard release there will also be an updated version of the BPM plugin available for download.
