### ISSUE TITLE
Classic Extra (2.0.7) error with Picard 2.3.2

### ISSUE THREAD

**Issue by jas01** [musicbrainz/picard-plugins#259]
From a clean install of Picard (2.3.2) on Arch Linux (python 3.8.3), if you activate the classic extra plugin and download this tag (at least)

https://musicbrainz.org/release/c44f2868-a2c2-4aa5-950b-a359357b612e

the info give this log 
```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/picard/album.py", line 430, in _finalize_loading_track
    run_track_metadata_processors(self, tm, track_node, self._release_node)
  File "/usr/lib/python3.8/site-packages/picard/metadata.py", line 484, in run_track_metadata_processors
    _track_metadata_processors.run(album_object, metadata, track, release)
  File "/usr/lib/python3.8/site-packages/picard/plugin.py", line 250, in run
    function(*args, **kwargs)
  File "/home/the_bear/.config/MusicBrainz/Picard/plugins/classical_extras.zip/classical_extras/__init__.py", line 4318, in add_work_info
    self.process_album(release_id, album)
  File "/home/the_bear/.config/MusicBrainz/Picard/plugins/classical_extras.zip/classical_extras/__init__.py", line 5672, in process_album
    work, movt, inter_work = self.derive_from_title(release_id, track, tm['title'])
  File "/home/the_bear/.config/MusicBrainz/Picard/plugins/classical_extras.zip/classical_extras/__init__.py", line 6577, in derive_from_title
    movt = title_split[1]
IndexError: list index out of range
```
All option of classic extra are at default value

Without this plugin, the import work fine.

Regards

**Comment by jas01** [comment]
Same error with [https://musicbrainz.org/release/bb36d6af-8e22-4bb1-a789-291e9d0a19be](url) I'm guessing it's the size of the album.

**Comment by jas01** [comment]
I find the problem. Just some indentation problem inside the plugin code. I create a pull request
[https://github.com/metabrainz/picard-plugins/pull/260](url)

**Comment by MetaTunes** [comment]
The actual problem is that the colon count is done on ':' and the split is done on ': ' so if there are colons without spaces after them, the two won't match. Also, the indentation is wrong on line 6586, but that is only a semantic error. I'll do a release with the fix. 
The main problem, however, is that the MB webservice does not provide all the information for very large releases such as this (I'm not sure what can be done about that) so that Classical Extras can't get the work details and will be of limited additional benefit to plain Picard. In the absence of links to the works, CE attempts to infer works from the positioning of colons in the titles and this is what was going wrong eventually. Do you actually own this release?! If so, congratulations! If not, is there an alternative (smaller) release which better matches your needs?

**Comment by MetaTunes** [comment]
Fixed in 2.0.11 - PR created

**Comment by jas01** [comment]
> from the positioning of colons in the titles and this is what was going wrong eventually. Do you actually own this release?! If so, congratulations! If not, is there an alternative (smaller) release which better matches your needs?

Thanks for the quick answer. 

Well no I don't own this release (I own the physical 100 cd instead ;-) ) and I'm really a beginner in picard/musicbrainz/etc... (I just learn those name  2 weeks ago). I own a small collection of cd, and currently trying to add those metadata on those 2000 cd...

Regards

**Comment by mineo** [comment]
#261 was merged.
